baseurl = "/"
languageCode = "en-us"
title = "Lovable Nerd"
theme = "hugo-zen"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/larryvincent"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lvincent"

[params]
    description = "A data science blog by Larry Vincent, Chief Brand Officer at UTA and marketing professor at the Marshall School of Business at USC."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
	  twitter   = "https://twitter.com/lvincent"
	  github    = "https://github.com/larryvincent/"
	  email     = "hello@laurencevincent.com"
